name: Deploy Docker image to AWS

on:
  workflow_run:
    workflows: ['Publish Docker Image']
    types: [completed]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Stop the old container
        run: docker stop modular-monolith-server || true

      - name: Delete the old container
        run: docker rm modular-monolith-server || true

      - name: Delete the old image
        run: docker rmi ${{secrets.DOCKERHUB_USERNAME}}/modular-monolith-server:latest || true

      - name: Pull the image from dockerhub
        run: docker pull ${{secrets.DOCKERHUB_USERNAME}}/modular-monolith-server:latest

      - name: Run the image
        run: |
          cd ./Modular-Monolith
          docker compose up -d