name: Deploy Docker Image to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{secrets.DOCKERHUB_TOKEN}}" | docker login -u "${{secrets.DOCKERHUB_USERNAME}}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/modular-monolith-server:latest .

      - name: Push Docker Image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/modular-monolith-server:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Deploy Container to Azure Web App
        run: |
          az webapp config container set --name ${{secrets.AZURE_WEBAPP_NAME}} \
            --resource-group ${{secrets.AZURE_RESOURCE_GROUP}} \
            --docker-custom-image-name ${{secrets.DOCKERHUB_USERNAME}}/modular-monolith-server:latest
