name: Publish Docker Image

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{secrets.DOCKERHUB_TOKEN}}" | docker login -u "${{secrets.DOCKERHUB_USERNAME}}" --password-stdin

      - name: Build Docker Image
        run: docker build --file ./Modular-Monolith/Dockerfile --tag ${{secrets.DOCKERHUB_USERNAME}}/modular-monolith-server:latest ./Modular-Monolith

      - name: Push Docker Image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/modular-monolith-server:latest